EditorSetupWindow.prototype.ClassControls.EditorSettingsControllerManager = class extends EditorSettingControlManager
{
}

EditorSetupWindow.prototype.ClassControls.EditorSettingsControllerManager.ORDER = 3;

var classEditorSettingControls = EditorSetupWindow.prototype.ClassControls.EditorSettingsControllerManager.prototype.ClassEditorSettingControls;
